{% set name = "treelib" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cbfffb2d2b75ccac27d0200cee0507b6fbb0726e0afb9fae017ade5d2ce8788

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future

test:
  imports:
    - treelib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/caesar0301/treelib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python 2/3 implementation of tree structure.

  description: |
    treelib is a simple tree data structure implementation in Python.
  doc_url: https://treelib.readthedocs.io/en/latest/
  dev_url: https://github.com/caesar0301/treelib

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
